name: Python app deploy on k8s
on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
        image-name:
          description: 'Docker image name with tag to deploy'
          required: true # This enables the manual "Run workflow" button
        #cron-image-name:
        #  description: 'Docker image name with tag for cron job to refresh secret'  
        #  required: true
        
jobs:
  Build-pythonapp-FLASK:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read    # Required for Checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2    

      - name: image creation and push to ecr
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: abhishek-ecr/abhishek-ecr
          TAG: v1.0.${{ github.run_number }}
          KUBECONFIG: ./kubeconfig.yaml
          image_name: ${{ github.event.inputs.image-name }}
          SECRET_NAME: ecr-pull-image-secret
          REGION: us-east-1
          TARGET_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          TARGET_NAMESPACE: default

        
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
          pwd
          export KUBECONFIG=$PWD/kubeconfig.yaml
          cat << EOF >> newrelic.ini
          [newrelic]
          license_key = 6811cbe35c008b8c4fb8e02b5c6a4025FFFFNRAL
          app_name = app-resume-display
          log_file = /tmp/newrelic-python-agent.log
          log_level = debug
          EOF
          docker build -f dockerfile -t $ECR_REGISTRY/$REPO:${{ github.event.inputs.image-name }}-${{ env.TAG }} .
          docker push $ECR_REGISTRY/$REPO:${{ github.event.inputs.image-name }}-${{ env.TAG }}
          pwd
          echo "702175642104.dkr.ecr.us-east-1.amazonaws.com/abhishek-ecr/abhishek-ecr:$image_name-$TAG"
          envsubst < app-deployment-template.yaml > python-app-deployment.yaml
          kubectl apply -f ./python-app-deployment.yaml --kubeconfig=./kubeconfig.yaml
          kubectl apply -f ./app-svc.yaml --kubeconfig=./kubeconfig.yaml
          #helm install step of ingress controller
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx --create-namespace \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/do-loadbalancer-enable-proxy-protocol"="true" \
          --set controller.config.use-proxy-protocol="true"

          kubectl apply -f ./ingress_routing.yaml --kubeconfig=./kubeconfig.yaml
          



  